### PR TITLE
SDE-1133: Send build notifications to GoDaddy slack

### PR DESCRIPTION
**Pull request by agrounds**

### CODE REVIEW

**Comment by DFStoneburner** [comment]
No! Stop committing specific company changes to a public repo @dturet @agrounds @zachschultz 

Fork it internally and make these changes privately.

**Review by DFStoneburner — CHANGES_REQUESTED** [review]
This is not appropriate for public repo's

**Comment by agrounds** [comment]
This repo is not intended to be consumable by anyone outside of GoDaddy. It has to be public because the pom is pushed to sonatype.

**Comment by DFStoneburner** [comment]
It was, originally, intended to be consumable. Move it to GDDY's internal repo.

**Comment by agrounds** [comment]
It hasn't been consumable since we added a dependency on Mainstreethub's fork of mysql-junit4, which was two years ago. And since we still need it to be in a public repo for sonatype, it has to stay here (for now at least).

**Pull request merged**
